@httpsHost=https://localhost:5002
@httpHost=http://localhost:5001
@postPath=shortenUrl

POST {{httpsHost}}/{{postPath}}
Content-Type: application/json

{
    "url": "https://www.google.com",
    "description": "¿Donde está mi mente?",
    "isPublic": true
}

###

GET {{httpsHost}}/99411910ce

###